### ISSUE TITLE
screenshot feature

### ISSUE THREAD

**Issue by becauseimnoob** [alexlaverty/ttsvibelounge#11]
![resim](https://user-images.githubusercontent.com/116311873/197342515-885aab57-314e-44f9-9d88-d1729198c6d1.png)
videos can look more modern with screenshots this feature is used at https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/screenshot_downloader.py

**Comment by anhdodotnet** [comment]
> 

Yes, I love this style too

**Comment by alexlaverty** [comment]
I have pushed some changes tonight, so that you can configure comments to be either text or reddit screenshots, self text will still be text thought, give it a try and see how you go.

**Comment by anhdodotnet** [comment]
> I have pushed some changes tonight, so that you can configure comments to be either text or reddit screenshots, self text will still be text thought, give it a try and see how you go.

I saw an Update, I tested it!

**Comment by anhdodotnet** [comment]
**First of all thanks for your enthusiasm, I really appreciate this :). A little review of the last major update new:**
- It is the most complete version ever
- TikTokTTS , edge-tts compiler
- Fix some bugs of the old version
- Big update is screenshot reddit
- .....
**I'm having a question is it possible for "screenshot reddit" to be enlarged? as shown (2)**
![image](https://user-images.githubusercontent.com/25850343/197817874-15139ef2-54d2-48ef-9486-f45ed33a9643.png)

![image](https://user-images.githubusercontent.com/25850343/197818341-d4bcab14-dc8f-4b2a-87cc-04a9d878d7e2.png)

**Comment by alexlaverty** [comment]
Thanks for the quick feedback, I'll have a look at enlarging the images. Tiktok speech engine still needs work because I believe it needs to be done in chunks of less than 300 characters, that's why you're getting errors for tiktok, anything over 300 will fail and produce empty mp3 file. Will probably need to write in chunks and then merge the mp3 files together or something.
For the others bug people are getting for the other videos, newscaster etc, I might need to echo out versions of peoples ffmpeg and moviepy libraries etc or do some more debug, not to sure why thats happening for people.

**Comment by alexlaverty** [comment]
Ok I've added a feature to resize the comment width and a setting to customize the width. I'll have a look at the rest of the stuff when I get some time.

**Comment by anhdodotnet** [comment]
> 



> Ok I've added a feature to resize the comment width and a setting to customize the width. I'll have a look at the rest of the stuff when I get some time.

Very good, I tried it and it works perfectly. however there is one problem that the backgrounds sometimes stop
[https://drive.google.com/file/d/19h-AJtIyP1d2fUZE-0e3FCKe4I5_5bAs/view?usp=sharing](url)
