### ISSUE TITLE
No video background ... ?

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#20]
video backgrouds is error?

![image](https://user-images.githubusercontent.com/25850343/198827408-cae28a41-fae4-4e82-9bc3-3541300359ff.png)
https://www.youtube.com/watch?v=LQaFy-FJCcY

**Comment by anhdodotnet** [comment]
Ok, I saw it in the config: enable_background = True

**Comment by alexlaverty** [comment]
Yeh today I worked on automating this script to run on a schedule via github Actions workflow :
https://github.com/alexlaverty/ttsvibelounge/blob/main/.github/workflows/tssvibelounge.yml

Turned off backgrounds because it greatly speeds up the compilation, i probably need to make more of these settings configurable via ENV overrides so it makes it easier to override these settings..

**Comment by anhdodotnet** [comment]
There is a problem: when we disable_upload = False
and total_posts_to_process = xxx
Then the tool will stop processing when it executes 1 video
![image](https://user-images.githubusercontent.com/25850343/198830564-e74c5c23-34a3-4aab-800d-4bf41d4127c5.png)

**Comment by alexlaverty** [comment]
I'll put some more checks in so it doesn't attempt to upload to youtube if the `client_secrets.json` file doesn't exist, 

if you want to enable auto upload to youtube you need to generate OAuth 2.0 token, and then save as `client_secrets.json` :
https://developers.google.com/youtube/registering_an_application

![image](https://user-images.githubusercontent.com/4024404/198858645-de0b0fb2-e30a-4426-be8a-ec2dff86d965.png)

**Comment by anhdodotnet** [comment]
I don't intend to upload it to the channel ... I just put the problem here that when disable_upload it will give the same error as above. thank you.
